trigger:
  tags:
    include:
    - release-*

pool:
    vmImage: 'ubuntu-latest'

steps: 
-   task: NodeTool@0
    displayName: 'Use Node 18.x'
    inputs: 
        versionSpec: 18.x
        checkLatest: true

-   task: Npm@1
    displayName: 'Install Node Package'
    inputs:
        command: install
    continueOnError: true

-   task: Npm@1
    displayName: 'Install Wrangler'
    inputs:
        command: custom
        verbose: false
        customCommand: 'i @cloudflare/wrangler -g'

-   powershell: 'npm run deploy -n -y'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cloudflare-poc'
    displayName: 'Powershell Script'
    env:
        CF_ACCOUNT_ID: $(cf_account_id)
        CF_APT_TOKEN: $(cf_account_token)
